extern const GeoLayout draco_cap_Normal_Cap_State_Switch_opt1[];
extern const GeoLayout draco_cap_Normal_Cap_State_Switch_opt2[];
extern const GeoLayout draco_cap_Normal_Cap_State_Switch_opt3[];
extern const GeoLayout draco_cap_geo[];
extern Lights1 draco_cap_trashpuyo_lights;
extern Lights1 draco_cap_trashpuyo_eye_lights;
extern Lights1 draco_cap_Metal_lights;
extern u8 draco_cap_puyo_rgba16[];
extern u8 draco_cap_puyo_eye_ia4[];
extern u8 draco_cap_Metal_Shade_rgba16_rgba16[];
extern u8 draco_cap_Metal_Light_rgba16_rgba16[];
extern Vtx draco_cap_Normal_Cap_DL_mesh_layer_5_vtx_0[30];
extern Gfx draco_cap_Normal_Cap_DL_mesh_layer_5_tri_0[];
extern Vtx draco_cap_Normal_Cap_DL_mesh_layer_5_vtx_1[25];
extern Gfx draco_cap_Normal_Cap_DL_mesh_layer_5_tri_1[];
extern Gfx mat_draco_cap_trashpuyo[];
extern Gfx mat_revert_draco_cap_trashpuyo[];
extern Gfx mat_draco_cap_trashpuyo_eye[];
extern Gfx mat_revert_draco_cap_trashpuyo_eye[];
extern Gfx mat_draco_cap_Metal[];
extern Gfx mat_revert_draco_cap_Metal[];
extern Gfx draco_cap_Normal_Cap_DL_mesh_layer_5[];
extern Gfx draco_cap_Normal_Cap_DL_mesh_layer_5_mat_override_Metal_0[];
