extern const GeoLayout h_wing_cap_Wing_Cap_Switch_opt1[];
extern const GeoLayout h_wing_cap_Wing_Cap_Switch_opt2[];
extern const GeoLayout h_wing_cap_Wing_Cap_Switch_opt3[];
extern const GeoLayout h_skl_wing_cap_geo[];
extern Lights1 h_wing_cap_CAP_lights;
extern Lights1 h_wing_cap_METAL_lights;
extern u8 h_wing_cap_Metal_Shade_rgba16_rgba16[];
extern u8 h_wing_cap_Metal_Light_rgba16_rgba16[];
extern u8 h_wing_cap_wing_2_rgba16[];
extern u8 h_wing_cap_wing1_rgba16[];
extern Vtx h_wing_cap_Wing_Cap_mesh_layer_1_vtx_0[158];
extern Gfx h_wing_cap_Wing_Cap_mesh_layer_1_tri_0[];
extern Vtx h_wing_cap_Wings_mesh_layer_4_vtx_0[8];
extern Gfx h_wing_cap_Wings_mesh_layer_4_tri_0[];
extern Vtx h_wing_cap_Wings_mesh_layer_4_vtx_1[8];
extern Gfx h_wing_cap_Wings_mesh_layer_4_tri_1[];
extern Gfx mat_h_wing_cap_CAP[];
extern Gfx mat_h_wing_cap_METAL[];
extern Gfx mat_revert_h_wing_cap_METAL[];
extern Gfx mat_h_wing_cap_Wing_Tip[];
extern Gfx mat_revert_h_wing_cap_Wing_Tip[];
extern Gfx mat_h_wing_cap_Wing_Base[];
extern Gfx mat_revert_h_wing_cap_Wing_Base[];
extern Gfx h_wing_cap_Wing_Cap_mesh_layer_1[];
extern Gfx h_wing_cap_Wing_Cap_mesh_layer_1_mat_override_METAL_0[];
extern Gfx h_wing_cap_Wings_mesh_layer_4[];
extern Gfx h_wing_cap_Wings_mesh_layer_4_mat_override_METAL_0[];
